### ISSUE TITLE
Improve support for touch

### ISSUE THREAD

**Issue by tandy-1000** [shaftoe/mixxx-numark-dj2go2-touch-mapping#1]
While the jog / pitchbend function works with the touch wheels, it would be nice to see this mapping make use of the touch functionality by differentiating between a 'touch jog' and a 'non touch jog'. This would be useful as the 'non touch jog' could work for faster jogging, with the 'touch jog' could be for slower fine tuning.

It would also be nice to see support for scratching using the touch wheels, as seen in pancake's mapping.

**Comment by shaftoe** [comment]
Hey @tandy-1000 , I'm sorry but I'm not using Mixxx anymore nor have any interest in supporting this project, if you're interested I'm happy to pass over the ownership to you, just let me know.

**Comment by tandy-1000** [comment]
I see, thank you, I am interested in trying to get this to work / taking ownership, but do not have any experience writing JavaScript, although I do know Nim, which can compile to JavaScript.
Do you have any guidance / advice on how to tackle this?

**Comment by shaftoe** [comment]
@tandy-1000 I'd recommend seeking advise on the Mixxx dev Zulip, it's quite active and I'm pretty sure there are people willing to help and with that kind of knowledge: 

- https://mixxx.org/contact/
- https://mixxx.zulipchat.com/login/

**Comment by tandy-1000** [comment]
I have got in contact with the zulip and have a preliminary mapping setup, just a few more things remaining. I'm happy to take ownership of the repo now.

**Comment by shaftoe** [comment]
![Screenshot 2021-07-13 at 12 06 01](https://user-images.githubusercontent.com/281389/125433708-f77c3a7d-64cd-4aaf-85fe-ccc5ae37e002.png)
@tandy-1000 enjoy!
